development:
  adapter: postgresql
  encoding: utf8
  database: test-guru_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: guru_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: test-guru_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
